### ISSUE TITLE
[Request] Add persistent settings

### ISSUE THREAD

**Issue by Drakonis96** [Drakonis96/plexytrack#201]
- Implement persistent settings support

**Comment by layezee20** [comment]
Hey I'm wondering when this will be implemented? I am suffering issues authing simkl and choosing a user, we've tried to change some settings to get it to work but no joy, I'm hoping this fix will solve the issues.

Too add on to this, I'm not sure you're aware but when passing the client ID for simkl regardless of what ID I put it gets passed as "None" and I have to manually add the ID to the URL

**Comment by akshara-tg** [comment]
My settings are not getting persisted..

added "PLEXYTRACK_DATA_DIR=/data" in .env file and below is my compose file

created the data directory in the same folder as compose.yaml
```
services:
  app:
    image: drakonis96/plexytrack
    container_name: plexytrack
    ports:
      - "5030:5030"
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
      - PLEX_BASEURL=${PLEX_BASEURL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - TRAKT_CLIENT_ID=${TRAKT_CLIENT_ID}
      - TRAKT_CLIENT_SECRET=${TRAKT_CLIENT_SECRET}
      - SIMKL_CLIENT_ID=${SIMKL_CLIENT_ID}
      - SIMKL_CLIENT_SECRET=${SIMKL_CLIENT_SECRET}
      - PLEXYTRACK_DATA_DIR=/data
    volumes:
      - ./data:/data
    restart: always
```
